### ISSUE TITLE
Канвертацыя слова "здароўе" ў лацінку

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizer#3]
Атрымліваецца "zdaroŭie", але павінна быць "zdaroŭje". Прыклады [тут](https://be.wikisource.org/wiki/%D0%A1%D1%82%D0%B0%D1%80%D0%BE%D0%BD%D0%BA%D0%B0%3AAbrazki_(1913).pdf/32) і [тут](https://be.wikisource.org/wiki/%D0%A1%D1%82%D0%B0%D1%80%D0%BE%D0%BD%D0%BA%D0%B0%3A%C4%8Ca%C5%82awiek_(1929).pdf/16).

**Comment by GooseOb** [comment]
выпраўлена
