### ISSUE TITLE
--latin mode ignores Cyrillic sequences in some cases 

### ISSUE THREAD

**Issue by coinvariant** [GooseOb/taraskevizer#9]
### Steps to reproduce
1. Run `tarask --latin`
2. Enter `<--[<*.ТУТ>]`
3. The result is `<--[<*.<*.ТУТ>>]`, whereas `<--[<*.ТУТ>]` was expected

Not only did conversion fail, but there is also duplication of characters.

**Comment by GooseOb** [comment]
As a temporary solution, you can try `-nec` (`--not-escape-caps`). By default capitalized words are wrapped in `<*.>` to avoid unwanted corrections in acronyms

**Comment by GooseOb** [comment]
Now, since `6.1.8` version, the result should be correct
